name: Bug report
description: Report a problem with crates.nvim
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        Before reporting make sure that both crates.nvim and its dependencies are
        updated to the latest version.
  - type: textarea
    attributes:
      label: "Description"
      description: "A comprehensive description of the problem you are reporting."
    validations:
      required: true
  - type: input
    attributes:
      label: "Neovim version"
      description: |
        Output of `nvim --version`
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system and version"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected:"
  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "Observed behavior (may optionally include logs, images, or videos)."
    validations:
      required: true
  - type: textarea
    attributes:
       label: "Minimal config"
       description: >
         Minimal(!) configuration necessary to reproduce the issue. Save this as
         `minimal.lua`. If necessary, add plugins and config options from your
         `init.lua` at the indicated lines.
       render: lua
       value: |
         local root = vim.fn.fnamemodify("crates_issue", ":p")
         for _, name in ipairs({ "config", "data", "state", "cache" }) do
             vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
         end

         local lazypath = root .. "/plugins/lazy.nvim"
         if not vim.loop.fs_stat(lazypath) then
             vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
         end
         vim.opt.runtimepath:prepend(lazypath)

         require("lazy").setup({
             {
                 "saecki/crates.nvim",
                 dependencies = "nvim-lua/plenary.nvim",
                 config = function()
                     require("crates").setup({
                         null_ls = {
                             enabled = true,
                         },
                         -- add crates.nvim config that is _necessary_ for reproducing the ISSUE
                     })
                 end,
             },
             {
                 "hrsh7th/nvim-cmp",
                 config = function()
                     require("cmp").setup({
                         sources = {
                             { name = "crates" },
                         },
                         -- add nvim-cmp config that is _necessary_ for reproducing the ISSUE
                     })
                 end,
             },
             {
                 "jose-elias-alvarez/null-ls.nvim",
                 config = function()
                     require("null-ls").setup({
                         null_ls = {
                             enabled = true,
                         },
                         -- add null-ls config that is _necessary_ for reproducing the ISSUE
                     })
                 end,
             },
             -- add additional plugins _necessary_ for reproducing the ISSUE
         }, {
             root = root .. "/plugins",
         })

         -- add init.lua settings that are _necessary_ for reproducing the ISSUE
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Cargo.toml"
      description: "The problematic `Cargo.toml` file"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config provided."
      value: |
        1. `nvim --clean -u minimal.lua`
        2. ...
    validations:
      required: true
